config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :real_estates
  root 'real_estates#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/real_estate.rb
class RealEstate < ApplicationRecord
  validates :street, :city, :zip, :state, :beds,
            :baths, :sq_ft, :type_of_estate,
            :sale_date, :price,
            :latitude, :longitude, presence: true
  validates :zip, :price, :latitude,
            :longitude, :sq_ft, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/real_estates_controller.rb
class RealEstatesController < ApplicationController
  def index
    @search = RealEstate.search(params[:q])
    @real_estates = @search.result(distinct: true).page params[:page]
  end

  def show
    @real_estate = RealEstate.find(params[:id])
  end

  def new
    @real_estate = RealEstate.new
  end

  def create
    @real_estate = RealEstate.new(real_estate_params)
    if @real_estate.save
      flash[:success] = "Created"
      redirect_to @real_estate
    else
      render 'new'
    end
  end

  def edit
    @real_estate = RealEstate.find(params[:id])
  end

  def update
    @real_estate = RealEstate.find(params[:id])
    if @real_estate.update_attributes(real_estate_params)
      flash[:success] = 'Data Updated'
      redirect_to @real_estate
    else
      render 'edit'
    end
  end

  def destroy
    RealEstate.find(params[:id]).destroy
    flash[:success] = 'Data Deleted'
    redirect_to real_estates_path
  end

  private

    def real_estate_params
      params.require(:real_estate).permit(:street, :city, :zip,
                                           :state, :beds, :baths,
                                           :sq_ft, :type_of_estate,
                                           :sale_date, :price, :latitude,
                                           :longitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/real_estate_helper.rb
module RealEstateHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Realestatetransaction</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield(:search) %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/real_estates/edit.html.haml
%div.container
  %div.row
    %div.jumbotron
      %h2.text-center Real Estate Detail Page
  %div.row
    %div.col-md-12
    = simple_form_for @real_estate do |r|
      = r.input :street, input_html: { class: 'form-control' }
      = r.input :city, input_html: { class: 'form-control' }
      = r.input :zip, input_html: { class: 'form-control' }
      = r.input :state, input_html: { class: 'form-control' }
      = r.input :beds, input_html: { class: 'form-control' }
      = r.input :sq_ft, input_html: { class: 'form-control' }
      = r.input :type_of_estate, input_html: { class: 'form-control' }
      = r.input :sale_date,
                 as: :date,
                 html5: true,
                 input_html: { class: 'form-control' }
      = r.input :price, input_html: { class: 'form-control' }
      = r.input :latitude, input_html: { class: 'form-control' }
      = r.input :longitude, input_html: { class: 'form-control' }

      = r.button :submit, input_html: { class: 'btn btn-lg btn-info'}

app/views/real_estates/index.html.haml
%div.container
  %div.row
    .col-md-offset-4.col-md-4
      - content_for :search do
        .col-md-offset-4.col-md-4
          = search_form_for @search do |f|
            = f.label 'Search Square Feet Greater Than'
            = f.text_field :sq_ft_gteq, class: 'form-control'
            %br
            = f.label 'Search Square Feet Lesser Than'
            = f.text_field :sq_ft_lteq, class: 'form-control'
            = f.submit 'Submit', class: 'btn btn-small btn-default'
  .row
    %div.jumbotron
      %h2.text-center Real Estate
      = link_to 'Create New', new_real_estate_path,
        class: 'btn btn-small btn-info'
  %div.row
    %div.col-md-12
      %table.table.table-hover
        %tr
          %td Street
          %td City
          %td Zip
          %td State
          %td Beds
          %td Baths
          %td Sq: Feet
          %td Type
          %td Sale Date
          %td Price
          %td Latitude
          %td Longitude
          %td Actions
        - @real_estates.each do |r|
          %tr
            %td= r.street
            %td= r.city
            %td= r.zip
            %td= r.state
            %td= r.beds
            %td= r.baths
            %td= r.sq_ft
            %td= r.type_of_estate
            %td= r.sale_date
            %td= r.price
            %td= r.latitude
            %td= r.longitude
            %td
              = link_to 'Show', real_estate_path(r.id),
                class: 'btn btn-small btn-info'

              = link_to 'Delete', { controller: :real_estates,
                action: 'destroy', id: r.id }, method: :delete,
                class: 'btn btn-small btn-danger'
      = paginate @real_estates

app/views/real_estates/new.html.haml
%div.container
  %div.row
    %div.jumbotron
      %h2.text-center Real Estate Detail Page
  %div.row
    %div.col-md-12
    = simple_form_for @real_estate do |r|
      = r.input :street, input_html: { class: 'form-control' }
      = r.input :city, input_html: { class: 'form-control' }
      = r.input :zip, input_html: { class: 'form-control' }
      = r.input :state, input_html: { class: 'form-control' }
      = r.input :beds, input_html: { class: 'form-control' }
      = r.input :sq_ft, input_html: { class: 'form-control' }
      = r.input :type_of_estate, input_html: { class: 'form-control' }
      = r.input :sale_date,
                as: :date,
                html5: true,
                input_html: { class: 'form-control' }
      = r.input :price, input_html: { class: 'form-control' }
      = r.input :latitude, input_html: { class: 'form-control' }
      = r.input :longitude, input_html: { class: 'form-control' }

      = r.button :submit, input_html: { class: 'btn btn-lg btn-info'}

app/views/real_estates/show.html.haml
%div.container
  %div.row
    %div.jumbotron
      %h2.text-center Real Estate Detail Page
  %div.row
    %div.col-md-12
      %p Street Name:
      %small= @real_estate.street
      %hr
      %p City Name:
      %small= @real_estate.city
      %hr
      %p Zip:
      %small= @real_estate.zip
      %hr
      %p State:
      %small= @real_estate.state
      %hr
      %p Beds:
      %small= @real_estate.beds
      %hr
      %p Baths:
      %small= @real_estate.baths
      %hr
      %p Square Feet:
      %small= @real_estate.sq_ft
      %hr
      %p Type of Estate:
      %small= @real_estate.type_of_estate
      %hr
      %p Sale Date:
      %small= @real_estate.sale_date
      %hr
      %p Price:
      %small= @real_estate.price
      %hr
      %p Latitude:
      %small= @real_estate.latitude
      %hr
      %p Longitude:
      %small= @real_estate.longitude
  = link_to 'Home Page', real_estates_path,
    class: 'btn btn-lg btn-info'
  = link_to 'Edit', edit_real_estate_path